import { catalogueCategories, type CatalogueCategory, type CatalogueService } from "./service-catalogue";

const categoryOverrides: Partial<Record<CatalogueService["category"], Partial<CatalogueCategory>>> = {
  "audit-assurance": {
    label: "Audit readiness & controls",
    shortLabel: "Audit & controls",
    description: "Audit preparation, internal controls, procurement testing and donor evidence support without misrepresenting preparation as an audit opinion.",
    regulatedNote: "FST preparation and internal-control support is not a statutory audit opinion. Regulated audit and assurance conclusions remain with an appropriately authorised practitioner or firm.",
  },
  "accounting-reporting": {
    label: "Accounting & finance operations",
    shortLabel: "Accounting",
    description: "Bookkeeping, bank and mobile-money reconciliation, payroll, close, financial statements, budgets and management reporting.",
  },
  "tax-payroll": {
    label: "RRA tax, payroll & RSSB",
    shortLabel: "RRA & RSSB",
    description: "Practical workpacks for VAT, EBM, WHT, PAYE, RSSB, CIT, PIT, IQP, clearances and RRA queries.",
    regulatedNote: "Rates, thresholds and portal steps are rechecked for the relevant period. Every declaration, tax position, payment and representation requires taxpayer approval and any applicable qualified-professional review before submission.",
  },
  "corporate-administration": {
    label: "RDB, governance & NGO compliance",
    shortLabel: "RDB & governance",
    description: "RDB/ORG setup and annual-return files, governance records, beneficial-ownership support, RGB NGO compliance and cooperative administration.",
    regulatedNote: "RDB, RGB, RCA, notarial, legal-personality and representation work is accepted only after the responsible route and any required legal or professional authority are confirmed.",
  },
  "management-risk": {
    label: "Business planning, risk & controls",
    shortLabel: "Planning & risk",
    description: "Bankable plans, feasibility cases, operating controls, policies and management tools designed for organisations and programmes.",
  },
  "loan-funding": {
    label: "Loans, grants & donor funding",
    shortLabel: "Loans & grants",
    description: "Loan and bankability files, BDF/BRD readiness, grant applications, MEAL frameworks, donor reporting and post-award controls.",
    regulatedNote: "FST prepares and quality-controls applications; it is not a lender or donor and cannot guarantee eligibility, approval, pricing, an award or disbursement. Submission remains applicant-controlled unless separately authorised.",
  },
};

export const rwandaCatalogueCategories: CatalogueCategory[] = catalogueCategories.map((category) => ({
  ...category,
  ...categoryOverrides[category.id],
}));

export const rwandaCatalogueServices: CatalogueService[] = [
  // Business planning, risk and controls
  {
    id: "rw-business-plan-model",
    category: "management-risk",
    title: "Bank-ready business plan and financial model",
    description: "Business case, market logic, operating plan and three-year integrated profit, cash-flow and funding projections for a straightforward SME.",
    from: 50_000,
    unit: "per plan",
    popular: true,
    tags: ["business plan", "financial model", "bank", "rdb", "investment", "sme"],
  },
  {
    id: "rw-feasibility-investment-case",
    category: "management-risk",
    title: "Feasibility study and investment case",
    description: "Demand, operating capacity, implementation, financial viability, sensitivities and evidence gaps for one defined investment project.",
    from: 90_000,
    unit: "per study",
    tags: ["feasibility", "investment", "market study", "project", "rdb"],
  },
  {
    id: "rw-risk-control-framework",
    category: "management-risk",
    title: "Risk and internal-control framework",
    description: "Risk register, owners, control activities, evidence, indicators and a management review calendar for one defined operation.",
    from: 40_000,
    unit: "per framework",
    tags: ["risk", "controls", "governance", "compliance", "risk register"],
  },
  {
    id: "rw-policy-sop-pack",
    category: "management-risk",
    title: "Policy and SOP implementation pack",
    description: "One practical policy, workflow, responsibility matrix, forms and implementation checklist for a finance or operating process.",
    from: 25_000,
    unit: "per process",
    tags: ["policy", "sop", "procedure", "workflow", "responsibility matrix"],
  },

  // Audit readiness and controls
  {
    id: "rw-financial-audit-readiness",
    category: "audit-assurance",
    title: "Financial-statement audit readiness pack",
    description: "Trial-balance checks, reconciliations, lead schedules, evidence index and review-point tracker for one reporting period.",
    from: 35_000,
    unit: "per reporting period",
    popular: true,
    regulated: true,
    tags: ["audit readiness", "financial statements", "pbc", "reconciliations", "evidence"],
  },
  {
    id: "rw-donor-audit-readiness",
    category: "audit-assurance",
    title: "Donor or grant audit readiness pack",
    description: "Expenditure, budget, procurement, payroll, asset and supporting-document files mapped to one grant agreement and audit request list.",
    from: 60_000,
    unit: "per project / period",
    regulated: true,
    tags: ["donor audit", "grant audit", "ngo", "procurement", "eligible expenditure", "pbc"],
  },
  {
    id: "rw-internal-audit-review",
    category: "audit-assurance",
    title: "Internal audit or controls review",
    description: "Risk-led walkthrough and testing of one process, with evidence-backed findings, owners, priorities and a remediation tracker.",
    from: 50_000,
    unit: "per process review",
    tags: ["internal audit", "controls", "process review", "findings", "remediation"],
  },
  {
    id: "rw-procurement-expenditure-review",
    category: "audit-assurance",
    title: "Procurement and expenditure compliance review",
    description: "Sample-based review of one procurement or expenditure population against approved thresholds, competition, allowability and evidence rules.",
    from: 45_000,
    unit: "per defined sample",
    tags: ["procurement", "expenditure", "donor", "allowability", "compliance", "sample testing"],
  },

  // Accounting and finance operations
  {
    id: "rw-accounting-setup",
    category: "accounting-reporting",
    title: "Accounting system and chart-of-accounts setup",
    description: "Opening balances, chart of accounts, document flow, bank/mobile-money structure and month-end checklist for one straightforward entity.",
    from: 20_000,
    unit: "per setup",
    tags: ["accounting setup", "chart of accounts", "opening balances", "finance process"],
  },
  {
    id: "rw-monthly-bookkeeping",
    category: "accounting-reporting",
    title: "Monthly bookkeeping and reconciliation",
    description: "Posting and coding of up to 50 complete transactions, one bank or mobile-money reconciliation and an exceptions list.",
    from: 7_500,
    unit: "per month",
    popular: true,
    tags: ["bookkeeping", "ledger", "bank", "mobile money", "reconciliation", "monthly"],
  },
  {
    id: "rw-catch-up-bookkeeping",
    category: "accounting-reporting",
    title: "Catch-up bookkeeping and records clean-up",
    description: "Reconstruction of one overdue month from complete statements and source documents, with missing-record and unreconciled-item lists.",
    from: 10_000,
    unit: "per month of records",
    tags: ["catch up", "backlog", "bookkeeping", "cleanup", "reconstruction"],
  },
  {
    id: "rw-bank-momo-reconciliation",
    category: "accounting-reporting",
    title: "Bank or mobile-money reconciliation",
    description: "Reconciliation of one bank, card, collection or mobile-money account with a dated list of unexplained differences.",
    from: 3_500,
    unit: "per account / month",
    tags: ["bank reconciliation", "mobile money", "momo", "merchant", "collections"],
  },
  {
    id: "rw-payroll-processing",
    category: "accounting-reporting",
    title: "Payroll processing and payslip pack",
    description: "Gross-to-net payroll, payroll register and payslips for up to 10 employees; RRA and RSSB declarations are separate unless bundled.",
    from: 6_000,
    unit: "per month",
    tags: ["payroll", "payslip", "gross to net", "employees", "salary"],
  },
  {
    id: "rw-management-accounts",
    category: "accounting-reporting",
    title: "Management accounts and cash report",
    description: "Profit and loss, balance sheet, cash position, budget comparison and concise management actions from reconciled records.",
    from: 17_500,
    unit: "per reporting period",
    tags: ["management accounts", "cash flow", "budget", "kpi", "monthly reporting"],
  },
  {
    id: "rw-year-end-financial-statements",
    category: "accounting-reporting",
    title: "Year-end close and financial statements",
    description: "Closing schedules and a review-ready financial-statement set for a straightforward entity with a clean trial balance and complete records.",
    from: 35_000,
    unit: "per year",
    tags: ["year end", "financial statements", "annual return", "ifrs for smes", "close"],
  },
  {
    id: "rw-budget-cashflow-model",
    category: "accounting-reporting",
    title: "Budget and rolling cash-flow forecast",
    description: "Twelve-month operating budget and cash forecast with opening position, receipts, commitments, funding needs and sensitivities.",
    from: 25_000,
    unit: "per model",
    tags: ["budget", "cash flow", "forecast", "liquidity", "scenario"],
  },
  {
    id: "rw-outsourced-finance-starter",
    category: "accounting-reporting",
    title: "SME monthly finance and compliance starter",
    description: "Up to 50 transactions, bookkeeping, one reconciliation, payroll for up to 10 staff, routine VAT/WHT/PAYE/RSSB workpacks and a monthly finance summary.",
    from: 25_000,
    unit: "per month",
    popular: true,
    regulated: true,
    tags: ["outsourced accounting", "monthly package", "bookkeeping", "vat", "wht", "paye", "rssb", "sme"],
  },

  // RRA tax, payroll and RSSB
  {
    id: "rw-tax-profile-health-check",
    category: "tax-payroll",
    title: "RRA taxpayer-profile and obligation health check",
    description: "Review of registration details, active tax types, filing calendar, available acknowledgements and an action list for a straightforward taxpayer.",
    from: 5_000,
    unit: "per taxpayer profile",
    regulated: true,
    tags: ["rra", "tax profile", "tin", "tax obligations", "compliance check"],
  },
  {
    id: "rw-vat-registration",
    category: "tax-payroll",
    title: "VAT registration or de-registration workpack",
    description: "Turnover test, evidence checklist and approval-ready application pack; RRA registration itself and official steps remain taxpayer-controlled.",
    from: 5_000,
    unit: "per application",
    regulated: true,
    tags: ["vat registration", "vat deactivation", "rra", "turnover threshold"],
  },
  {
    id: "rw-vat-return",
    category: "tax-payroll",
    title: "VAT return and EBM reconciliation",
    description: "One routine VAT workpack reconciled to EBM sales, purchase evidence, ledger balances and the applicable monthly or quarterly period.",
    from: 4_500,
    unit: "per return",
    popular: true,
    regulated: true,
    tags: ["vat", "rra", "ebm", "return", "sales", "purchases", "reconciliation"],
  },
  {
    id: "rw-wht-return",
    category: "tax-payroll",
    title: "Withholding tax (WHT) declaration workpack",
    description: "One WHT schedule for routine payments, reconciled to supplier, contract, invoice and payment evidence before approval.",
    from: 3_500,
    unit: "per declaration",
    regulated: true,
    tags: ["wht", "withholding tax", "3 percent", "15 percent", "rra", "supplier"],
  },
  {
    id: "rw-paye-return",
    category: "tax-payroll",
    title: "PAYE declaration workpack",
    description: "One PAYE computation and declaration schedule for up to 10 employees, reconciled to the approved payroll register.",
    from: 3_500,
    unit: "per declaration",
    regulated: true,
    tags: ["paye", "employment tax", "payroll", "rra", "employees"],
  },
  {
    id: "rw-rssb-declaration",
    category: "tax-payroll",
    title: "RSSB contribution declaration workpack",
    description: "Pension, occupational-hazard and applicable scheme schedules for up to 10 employees, reconciled to payroll and current contribution rules.",
    from: 3_500,
    unit: "per declaration",
    regulated: true,
    tags: ["rssb", "pension", "occupational hazards", "maternity", "medical", "contributions"],
  },
  {
    id: "rw-unified-paye-rssb",
    category: "tax-payroll",
    title: "Unified PAYE and RSSB declaration pack",
    description: "Combined PAYE and RSSB annexure, payroll reconciliation and approval checklist for up to 10 employees.",
    from: 6_000,
    unit: "per month",
    popular: true,
    regulated: true,
    tags: ["unified declaration", "paye", "rssb", "payroll", "etax", "myrra"],
  },
  {
    id: "rw-monthly-rra-rssb-bundle",
    category: "tax-payroll",
    title: "Monthly RRA and RSSB compliance bundle",
    description: "Routine VAT, WHT, PAYE and RSSB workpacks for one small entity with up to 10 employees, provided from clean ledgers and payroll data.",
    from: 15_000,
    unit: "per month",
    popular: true,
    regulated: true,
    tags: ["monthly tax", "vat", "wht", "paye", "rssb", "compliance package"],
  },
  {
    id: "rw-cit-return",
    category: "tax-payroll",
    title: "Corporate income tax (CIT) computation and return",
    description: "Annual CIT computation, tax reconciliation, annexures and evidence file for a straightforward company with final reconciled accounts.",
    from: 17_500,
    unit: "per tax year",
    regulated: true,
    tags: ["cit", "corporate income tax", "annual return", "rra", "tax computation"],
  },
  {
    id: "rw-pit-return",
    category: "tax-payroll",
    title: "Personal or sole-trader income tax (PIT) return",
    description: "Annual PIT computation and return workpack from complete income, expense and supporting records for one straightforward taxpayer.",
    from: 10_000,
    unit: "per tax year",
    regulated: true,
    tags: ["pit", "personal income tax", "sole trader", "annual return", "rra"],
  },
  {
    id: "rw-iqp-prepayment",
    category: "tax-payroll",
    title: "Income tax quarterly prepayment (IQP) workpack",
    description: "One quarterly prepayment computation reconciled to prior tax, current turnover and available withholding evidence.",
    from: 5_000,
    unit: "per quarter",
    regulated: true,
    tags: ["iqp", "quarterly prepayment", "income tax", "rra", "turnover"],
  },
  {
    id: "rw-ebm-setup-review",
    category: "tax-payroll",
    title: "EBM setup and compliance review",
    description: "EBM route selection, setup evidence, sales-invoice controls and EBM-to-ledger exception review for one location or device.",
    from: 7_500,
    unit: "per location / device",
    regulated: true,
    tags: ["ebm", "electronic billing", "eis", "invoice", "rra", "sales"],
  },
  {
    id: "rw-clearance-readiness",
    category: "tax-payroll",
    title: "RRA tax and RSSB clearance readiness",
    description: "Filing, payment, arrears and evidence review with an issue list before the taxpayer requests the relevant clearance certificate.",
    from: 7_500,
    unit: "per readiness review",
    regulated: true,
    tags: ["tcc", "tax clearance", "rssb clearance", "loan", "tender", "arrears"],
  },
  {
    id: "rw-rra-query-response",
    category: "tax-payroll",
    title: "RRA query, desk audit or assessment response pack",
    description: "Issue chronology, reconciliations, source evidence and draft response for one defined RRA query; objection or litigation scope is quoted separately.",
    from: 30_000,
    unit: "per defined matter",
    regulated: true,
    tags: ["rra query", "tax audit", "assessment", "response", "reconciliation", "objection"],
  },

  // RDB, governance and NGO compliance
  {
    id: "rw-rdb-business-registration",
    category: "corporate-administration",
    title: "RDB business-registration readiness pack",
    description: "Entity, ownership, activity, director and supporting-information pack for a straightforward online RDB/ORG registration; the official registration service is free.",
    from: 7_500,
    unit: "per entity",
    regulated: true,
    tags: ["rdb", "org", "business registration", "company", "enterprise", "ownership"],
  },
  {
    id: "rw-post-registration-starter",
    category: "corporate-administration",
    title: "Post-registration compliance starter pack",
    description: "First obligation calendar covering tax profile, VAT assessment, EBM, payroll/RSSB, records, annual returns and responsible owners.",
    from: 15_000,
    unit: "per entity",
    tags: ["post registration", "compliance calendar", "rra", "rssb", "ebm", "annual return"],
  },
  {
    id: "rw-org-annual-return",
    category: "corporate-administration",
    title: "ORG annual return and good-standing readiness",
    description: "Annual-return checklist, current financial information, resolutions and missing-filing review before the company-controlled submission.",
    from: 10_000,
    unit: "per year",
    regulated: true,
    tags: ["annual return", "good standing", "rdb", "org", "financial statements"],
  },
  {
    id: "rw-governance-beneficial-ownership",
    category: "corporate-administration",
    title: "Governance and beneficial-ownership records pack",
    description: "Ownership information, resolutions, meeting records, action tracker and controlled registers for one straightforward entity update.",
    from: 17_500,
    unit: "per update pack",
    regulated: true,
    tags: ["beneficial ownership", "board minutes", "resolutions", "registers", "governance"],
  },
  {
    id: "rw-ngo-rgb-compliance",
    category: "corporate-administration",
    title: "RGB NGO annual compliance pack",
    description: "Annual report, action plan, budget, source-of-funds schedule, governance evidence and submission checklist aligned to the current RGB route.",
    from: 30_000,
    unit: "per annual pack",
    popular: true,
    regulated: true,
    tags: ["rgb", "ngo", "annual report", "action plan", "budget", "source of funds", "compliance"],
  },
  {
    id: "rw-cooperative-governance",
    category: "corporate-administration",
    title: "Cooperative governance and member-record pack",
    description: "Meeting, resolution, member, contribution, action and compliance records organised for one cooperative reporting cycle.",
    from: 25_000,
    unit: "per reporting cycle",
    tags: ["cooperative", "rca", "members", "governance", "contributions", "records"],
  },

  // Loans, grants and donor funding
  {
    id: "rw-loan-readiness-diagnostic",
    category: "loan-funding",
    title: "Business-loan readiness diagnostic",
    description: "Business-purpose, registration, tax/RSSB, records, cash-flow, debt, CRB-consent and collateral-gap checklist with a bankability action plan.",
    from: 15_000,
    unit: "per applicant",
    popular: true,
    tags: ["loan readiness", "bankability", "tcc", "rssb", "crb", "collateral", "diagnostic"],
  },
  {
    id: "rw-loan-application-package",
    category: "loan-funding",
    title: "Loan application support package",
    description: "Application letter, business profile, funding purpose, document index, financial schedules and lender-query checklist for one defined facility.",
    from: 50_000,
    unit: "per application",
    popular: true,
    tags: ["loan application", "bank", "application letter", "financial schedules", "lender pack"],
  },
  {
    id: "rw-bankability-file",
    category: "loan-funding",
    title: "Bankability and standardised application file",
    description: "Full evidence-led credit file covering business, ownership, purpose, financial performance, repayment capacity, existing debt, security and unresolved risks.",
    from: 80_000,
    unit: "per credit file",
    tags: ["bankability", "credit file", "standardised application file", "repayment", "collateral", "credit memo"],
  },
  {
    id: "rw-dscr-repayment-model",
    category: "loan-funding",
    title: "Loan cash-flow, DSCR and repayment model",
    description: "Funding-use schedule, operating cash flow, debt-service capacity, repayment scenarios and sensitivity analysis for one proposed facility.",
    from: 30_000,
    unit: "per model",
    tags: ["dscr", "repayment", "cash flow", "loan model", "sensitivity", "debt service"],
  },
  {
    id: "rw-bdf-guarantee-readiness",
    category: "loan-funding",
    title: "BDF guarantee and collateral-gap readiness",
    description: "Eligibility and evidence pack for a proposed BDF-supported route, including financing gap, applicant contribution, lender dependencies and unresolved conditions.",
    from: 45_000,
    unit: "per application route",
    tags: ["bdf", "guarantee", "collateral gap", "sme finance", "eligibility"],
  },
  {
    id: "rw-brd-dfi-financing",
    category: "loan-funding",
    title: "BRD or DFI project-finance readiness pack",
    description: "Project narrative, implementation plan, multi-year projections, funding structure, evidence index and due-diligence action list for one defined programme.",
    from: 120_000,
    unit: "per project",
    tags: ["brd", "dfi", "project finance", "investment", "due diligence", "projections"],
  },
  {
    id: "rw-grant-readiness-diagnostic",
    category: "loan-funding",
    title: "Donor and grant readiness diagnostic",
    description: "Eligibility, registration, governance, safeguarding, finance, procurement, MEAL and evidence-gap review against one target funding route.",
    from: 25_000,
    unit: "per organisation / call",
    popular: true,
    tags: ["grant readiness", "donor", "ngo", "eligibility", "safeguarding", "meal"],
  },
  {
    id: "rw-grant-application-package",
    category: "loan-funding",
    title: "Full grant or donor application package",
    description: "Eligibility screen, compliant narrative, workplan, results framework, budget, risk register, evidence map and submission checklist for one standard call.",
    from: 85_000,
    unit: "per application",
    popular: true,
    tags: ["grant application", "donor proposal", "budget", "workplan", "results framework", "submission"],
  },
  {
    id: "rw-logframe-meal-budget",
    category: "loan-funding",
    title: "Logframe, MEAL framework and donor budget pack",
    description: "Theory of change, results chain, indicators, means of verification, activity schedule and costed budget for one defined project concept.",
    from: 50_000,
    unit: "per project",
    tags: ["logframe", "meal", "mel", "indicators", "theory of change", "donor budget"],
  },
  {
    id: "rw-post-award-grant-controls",
    category: "loan-funding",
    title: "Post-award grant controls and mobilisation pack",
    description: "Grant chart of accounts, budget-control file, procurement plan, reporting calendar, responsibility matrix and evidence structure for one award.",
    from: 70_000,
    unit: "per award",
    tags: ["post award", "grant controls", "procurement plan", "budget control", "reporting calendar"],
  },
  {
    id: "rw-donor-reporting-pack",
    category: "loan-funding",
    title: "Donor financial and narrative reporting pack",
    description: "Budget-to-actual reconciliation, expenditure schedule, results update, variance explanations, evidence index and approval checklist for one reporting period.",
    from: 50_000,
    unit: "per report",
    tags: ["donor report", "financial report", "narrative report", "budget variance", "evidence"],
  },
];
