export const catalogueCategories = [
  {
    id: "audit-assurance",
    label: "Audit & assurance",
    shortLabel: "Audit",
    description: "Independent and evidence-led work for statutory, funder, governance and control requirements.",
    regulatedNote: "Statutory audit and assurance work is accepted only through an appropriately authorised Malta auditor or audit firm after independence and conflict checks.",
  },
  {
    id: "accounting-reporting",
    label: "Accounting & reporting",
    shortLabel: "Accounting",
    description: "Reliable records, reconciliations, year-end accounts and decision-ready management reporting.",
  },
  {
    id: "tax-payroll",
    label: "Tax, VAT & payroll",
    shortLabel: "Tax & payroll",
    description: "Recurring and one-off Malta compliance support for businesses, employers and individuals.",
    regulatedNote: "Final filings, positions and submissions remain subject to client approval and any applicable professional requirements.",
  },
  {
    id: "corporate-administration",
    label: "Corporate administration",
    shortLabel: "Corporate",
    description: "Company formation, statutory records, resolutions, filings and recurring governance administration.",
    regulatedNote: "Company-service-provider activities are delivered only where the required Malta authorisation, registration or exemption is in place.",
  },
  {
    id: "management-risk",
    label: "Management, risk & controls",
    shortLabel: "Advisory",
    description: "Practical plans, policies, controls and performance tools that management can put to work.",
  },
  {
    id: "loan-funding",
    label: "Loans & funding",
    shortLabel: "Funding",
    description: "End-to-end readiness, applications, financial schedules, evidence packs and award setup.",
  },
  {
    id: "legal-contracts",
    label: "Legal & contract support",
    shortLabel: "Contracts",
    description: "Commercial document drafting, review and plain-language risk support for everyday business needs.",
    regulatedNote: "Legal advice, opinions and Malta-law work requiring an advocate are reviewed or delivered by an appropriately warranted legal professional.",
  },
] as const;

export type CatalogueCategoryId = (typeof catalogueCategories)[number]["id"];

export type CatalogueService = {
  id: string;
  category: CatalogueCategoryId;
  title: string;
  description: string;
  from: number;
  unit: string;
  popular?: boolean;
  free?: boolean;
  regulated?: boolean;
  tags: string[];
};

export const catalogueServices: CatalogueService[] = [
  {
    id: "statutory-audit",
    category: "audit-assurance",
    title: "Statutory financial statement audit",
    description: "Risk-based audit of a straightforward small Malta company, including planning, fieldwork and the statutory auditor’s report.",
    from: 450,
    unit: "per year",
    popular: true,
    regulated: true,
    tags: ["company audit", "annual audit", "financial statements", "malta"],
  },
  {
    id: "voluntary-audit",
    category: "audit-assurance",
    title: "Voluntary financial statement audit",
    description: "Independent audit requested by owners, lenders, investors or group management where no statutory mandate applies.",
    from: 400,
    unit: "per engagement",
    regulated: true,
    tags: ["independent audit", "lender", "investor", "financial statements"],
  },
  {
    id: "limited-assurance-review",
    category: "audit-assurance",
    title: "Limited assurance or review engagement",
    description: "A narrower independent conclusion over specified financial information, designed around the intended users and criteria.",
    from: 350,
    unit: "per engagement",
    regulated: true,
    tags: ["review", "assurance", "financial information"],
  },
  {
    id: "agreed-upon-procedures",
    category: "audit-assurance",
    title: "Agreed-upon procedures",
    description: "Factual findings from procedures agreed with management, a lender, donor or other specified party.",
    from: 300,
    unit: "per assignment",
    regulated: true,
    tags: ["aup", "factual findings", "lender", "donor"],
  },
  {
    id: "internal-audit-health-check",
    category: "audit-assurance",
    title: "Internal audit health check",
    description: "Focused review of one process or risk area, with practical findings, owners and prioritised actions.",
    from: 350,
    unit: "per review",
    popular: true,
    tags: ["internal audit", "process review", "risk", "governance"],
  },
  {
    id: "internal-controls-assurance",
    category: "audit-assurance",
    title: "Internal controls assurance",
    description: "Design and operating-effectiveness testing over a defined control set, with an evidence-backed report.",
    from: 400,
    unit: "per control area",
    tags: ["controls", "testing", "assurance", "coso"],
  },
  {
    id: "grant-donor-project-audit",
    category: "audit-assurance",
    title: "Grant, donor or project audit",
    description: "Expenditure, eligibility and compliance testing against the funding agreement and reporting framework.",
    from: 500,
    unit: "per project",
    regulated: true,
    tags: ["grant audit", "donor audit", "project audit", "eligible costs"],
  },
  {
    id: "ngo-voluntary-audit",
    category: "audit-assurance",
    title: "NGO or voluntary organisation audit",
    description: "Proportionate audit for charities, associations and voluntary organisations, including restricted-fund considerations.",
    from: 450,
    unit: "per year",
    regulated: true,
    tags: ["ngo", "charity", "voluntary organisation", "restricted funds"],
  },
  {
    id: "compliance-audit",
    category: "audit-assurance",
    title: "Compliance or regulatory audit",
    description: "Testing of a defined obligation set, licence condition, policy framework or contractual requirement.",
    from: 450,
    unit: "per review",
    tags: ["compliance", "regulation", "licence", "policy"],
  },
  {
    id: "systems-data-audit",
    category: "audit-assurance",
    title: "Systems and data audit",
    description: "Review of access, change, interface, data-quality and reporting controls over a defined system landscape.",
    from: 550,
    unit: "per system",
    tags: ["it audit", "data", "access controls", "systems"],
  },
  {
    id: "audit-readiness",
    category: "audit-assurance",
    title: "Audit readiness and remediation",
    description: "Working-paper, reconciliation and evidence review before an external audit, with a sequenced closeout list.",
    from: 250,
    unit: "per close",
    tags: ["audit preparation", "working papers", "reconciliations", "remediation"],
  },
  {
    id: "fraud-risk-review",
    category: "audit-assurance",
    title: "Fraud-risk or special-purpose review",
    description: "Scoped fact-finding, transaction analysis and control review for a defined concern or allegation.",
    from: 500,
    unit: "per assignment",
    tags: ["fraud risk", "investigation", "transactions", "special review"],
  },

  {
    id: "monthly-bookkeeping",
    category: "accounting-reporting",
    title: "Monthly bookkeeping",
    description: "Posting, coding and ledger maintenance for up to 50 straightforward transactions, with monthly bank reconciliation.",
    from: 100,
    unit: "per month",
    popular: true,
    tags: ["bookkeeping", "general ledger", "bank reconciliation", "monthly"],
  },
  {
    id: "catch-up-bookkeeping",
    category: "accounting-reporting",
    title: "Catch-up bookkeeping",
    description: "Reconstruction and clean-up of overdue records from complete source documents and bank statements.",
    from: 150,
    unit: "per month of records",
    tags: ["backlog", "cleanup", "reconstruction", "overdue books"],
  },
  {
    id: "bank-reconciliation",
    category: "accounting-reporting",
    title: "Standalone bank reconciliation",
    description: "Monthly reconciliation of one bank, card or payment account, including an exceptions list.",
    from: 30,
    unit: "per account / month",
    tags: ["bank", "card", "payment account", "reconciliation"],
  },
  {
    id: "annual-financial-statements",
    category: "accounting-reporting",
    title: "Annual financial statements",
    description: "Preparation of a straightforward year-end financial statement set from a clean trial balance and complete records.",
    from: 300,
    unit: "per year",
    popular: true,
    tags: ["annual accounts", "financial statements", "year end", "reporting"],
  },
  {
    id: "management-accounts",
    category: "accounting-reporting",
    title: "Management accounts",
    description: "Monthly or quarterly profit and loss, balance sheet, cash summary and short management commentary.",
    from: 150,
    unit: "per reporting period",
    tags: ["management reporting", "monthly accounts", "kpi", "finance"],
  },
  {
    id: "cashflow-forecast",
    category: "accounting-reporting",
    title: "Cash-flow forecast",
    description: "Rolling cash forecast built from opening balances, expected receipts, commitments and scenario assumptions.",
    from: 180,
    unit: "per model",
    tags: ["cash flow", "forecast", "liquidity", "scenario"],
  },
  {
    id: "budget-projection-model",
    category: "accounting-reporting",
    title: "Budget and projection model",
    description: "Integrated profit and loss, balance sheet and cash-flow projections with clear operating assumptions.",
    from: 300,
    unit: "per model",
    tags: ["budget", "forecast", "projections", "financial model"],
  },
  {
    id: "group-consolidation",
    category: "accounting-reporting",
    title: "Group consolidation",
    description: "Consolidation of a small group from aligned reporting packs, including core elimination entries.",
    from: 500,
    unit: "per reporting period",
    tags: ["group accounts", "consolidation", "eliminations", "reporting pack"],
  },
  {
    id: "finance-policies",
    category: "accounting-reporting",
    title: "Finance policy or close procedure",
    description: "A practical policy, checklist and responsibility map for one finance process or month-end close.",
    from: 200,
    unit: "per process",
    tags: ["finance policy", "close", "procedure", "checklist"],
  },
  {
    id: "fractional-controller",
    category: "accounting-reporting",
    title: "Fractional finance controller",
    description: "Recurring senior review of books, close quality, management reporting and priority finance actions.",
    from: 350,
    unit: "per month",
    tags: ["controller", "finance manager", "review", "oversight"],
  },

  {
    id: "tax-vat-registration",
    category: "tax-payroll",
    title: "Tax or VAT registration",
    description: "Preparation of one straightforward business or individual registration from complete information.",
    from: 60,
    unit: "per registration",
    tags: ["tax registration", "vat registration", "taxpayer setup"],
  },
  {
    id: "vat-return",
    category: "tax-payroll",
    title: "VAT return and reconciliation",
    description: "Preparation of a straightforward VAT return reconciled to the underlying ledger before client approval.",
    from: 45,
    unit: "per return",
    popular: true,
    tags: ["vat", "return", "reconciliation", "filing"],
  },
  {
    id: "vies-intrastat",
    category: "tax-payroll",
    title: "VIES or Intrastat filing",
    description: "Preparation of one routine EU transaction statement from clean and complete transaction data.",
    from: 30,
    unit: "per filing",
    tags: ["vies", "intrastat", "eu", "statement"],
  },
  {
    id: "corporate-tax-return",
    category: "tax-payroll",
    title: "Corporate income tax return",
    description: "Tax computation and return for a straightforward Malta company from final, reconciled accounts.",
    from: 180,
    unit: "per year",
    popular: true,
    tags: ["corporate tax", "company return", "tax computation"],
  },
  {
    id: "personal-tax-return",
    category: "tax-payroll",
    title: "Personal or self-employed tax return",
    description: "Preparation of a straightforward annual return from complete income, expense and supporting records.",
    from: 100,
    unit: "per year",
    tags: ["personal tax", "self employed", "individual", "annual return"],
  },
  {
    id: "tax-computation-review",
    category: "tax-payroll",
    title: "Tax computation review",
    description: "Independent review of one draft computation, key adjustments and supporting schedules.",
    from: 150,
    unit: "per computation",
    tags: ["tax review", "computation", "adjustments"],
  },
  {
    id: "payroll-setup",
    category: "tax-payroll",
    title: "Payroll and FSS setup",
    description: "Employer and employee setup, payroll calendar, core data checks and opening payroll configuration.",
    from: 75,
    unit: "per employer",
    tags: ["payroll setup", "fss", "employer", "employees"],
  },
  {
    id: "monthly-payroll",
    category: "tax-payroll",
    title: "Monthly payroll processing",
    description: "Gross-to-net payroll, payslips and routine payroll summary from approved monthly inputs.",
    from: 10,
    unit: "per employee / month",
    popular: true,
    tags: ["payroll", "payslips", "gross to net", "employees"],
  },
  {
    id: "fss-filings",
    category: "tax-payroll",
    title: "FSS filing support",
    description: "Preparation of recurring employer FSS information and year-end employee/employer summaries.",
    from: 35,
    unit: "per month",
    tags: ["fss", "fs5", "fs3", "payroll tax"],
  },
  {
    id: "tax-refund-claim",
    category: "tax-payroll",
    title: "Tax refund or credit claim",
    description: "Preparation of a straightforward refund or credit application with an indexed supporting pack.",
    from: 150,
    unit: "per claim",
    tags: ["refund", "tax credit", "shareholder refund", "claim"],
  },
  {
    id: "cross-border-withholding",
    category: "tax-payroll",
    title: "Cross-border payment and withholding review",
    description: "Review of one payment flow, treaty position, documentation and practical withholding steps.",
    from: 180,
    unit: "per payment flow",
    tags: ["withholding tax", "cross border", "treaty", "payment"],
  },
  {
    id: "transfer-pricing-file",
    category: "tax-payroll",
    title: "Transfer-pricing documentation",
    description: "A proportionate local support file for a straightforward related-party transaction and pricing policy.",
    from: 750,
    unit: "per transaction type",
    tags: ["transfer pricing", "related party", "local file", "international tax"],
  },
  {
    id: "tax-query-objection",
    category: "tax-payroll",
    title: "MTCA query, review or objection support",
    description: "Issue assessment, response pack and draft correspondence for one defined authority matter.",
    from: 250,
    unit: "per matter",
    tags: ["mtca", "tax query", "objection", "authority"],
  },

  {
    id: "company-formation",
    category: "corporate-administration",
    title: "Malta company formation",
    description: "Formation pack, constitutional documents, registrations and setup checklist for a straightforward structure.",
    from: 650,
    unit: "professional fee",
    popular: true,
    regulated: true,
    tags: ["incorporation", "company formation", "malta", "startup"],
  },
  {
    id: "company-secretary",
    category: "corporate-administration",
    title: "Company secretary service",
    description: "Recurring statutory calendar, board support and core company-secretarial administration.",
    from: 250,
    unit: "per year",
    regulated: true,
    tags: ["company secretary", "governance", "annual", "csp"],
  },
  {
    id: "annual-return",
    category: "corporate-administration",
    title: "MBR annual return preparation",
    description: "Preparation of one routine annual return from verified corporate records, excluding registry charges.",
    from: 75,
    unit: "per filing",
    tags: ["mbr", "annual return", "company filing"],
  },
  {
    id: "beneficial-owner-filing",
    category: "corporate-administration",
    title: "Beneficial-owner filing update",
    description: "Preparation of a routine beneficial-ownership update from approved and verified information.",
    from: 60,
    unit: "per filing",
    tags: ["beneficial owner", "ubo", "mbr", "filing"],
  },
  {
    id: "corporate-records",
    category: "corporate-administration",
    title: "Statutory registers maintenance",
    description: "Initial clean-up or annual maintenance of core company registers from complete source records.",
    from: 120,
    unit: "per year",
    tags: ["statutory registers", "company records", "governance"],
  },
  {
    id: "board-resolutions",
    category: "corporate-administration",
    title: "Board or shareholder resolutions",
    description: "Drafting of a routine approval pack, minutes template and action checklist for one corporate decision.",
    from: 80,
    unit: "per pack",
    tags: ["board", "shareholder", "resolution", "minutes"],
  },
  {
    id: "share-change",
    category: "corporate-administration",
    title: "Share issue, transfer or capital change",
    description: "Corporate-document and filing support for one straightforward ownership or capital action.",
    from: 150,
    unit: "per action",
    regulated: true,
    tags: ["shares", "allotment", "transfer", "capital"],
  },
  {
    id: "officer-address-change",
    category: "corporate-administration",
    title: "Officer or registered-detail change",
    description: "Preparation of a routine director, secretary, registered-office or company-detail update.",
    from: 75,
    unit: "per change",
    regulated: true,
    tags: ["director", "secretary", "address", "mbr"],
  },
  {
    id: "strike-off-restoration",
    category: "corporate-administration",
    title: "Strike-off or restoration support",
    description: "Readiness review, document checklist and process support for a straightforward closure or restoration.",
    from: 250,
    unit: "per process",
    regulated: true,
    tags: ["strike off", "restoration", "company closure"],
  },

  {
    id: "business-plan",
    category: "management-risk",
    title: "Business-plan preparation",
    description: "Decision-ready business plan with market, operating model, implementation roadmap, risks and integrated projections.",
    from: 900,
    unit: "per plan",
    popular: true,
    tags: ["business plan", "strategy", "market", "financial projections"],
  },
  {
    id: "business-plan-review",
    category: "management-risk",
    title: "Business-plan review",
    description: "Structured challenge of an existing plan, with evidence gaps, inconsistencies and recommended revisions.",
    from: 250,
    unit: "per plan",
    tags: ["business plan", "review", "challenge", "recommendations"],
  },
  {
    id: "feasibility-study",
    category: "management-risk",
    title: "Feasibility study",
    description: "Commercial, operational and financial feasibility assessment for a defined initiative or investment.",
    from: 500,
    unit: "per study",
    tags: ["feasibility", "investment", "commercial", "operations"],
  },
  {
    id: "strategy-workshop",
    category: "management-risk",
    title: "Management strategy workshop",
    description: "Facilitated working session that turns priorities into decisions, owners, measures and a 90-day action plan.",
    from: 300,
    unit: "per workshop",
    tags: ["strategy", "workshop", "roadmap", "management"],
  },
  {
    id: "internal-control-review",
    category: "management-risk",
    title: "Internal-control review",
    description: "Process walkthrough, risk-control map, design-gap assessment and prioritised remediation plan.",
    from: 600,
    unit: "per process",
    popular: true,
    tags: ["internal controls", "risk control matrix", "remediation", "process"],
  },
  {
    id: "sop-process-document",
    category: "management-risk",
    title: "Procedure or SOP drafting",
    description: "Clear, role-based procedure for one process, including inputs, controls, outputs and escalation points.",
    from: 200,
    unit: "per process",
    tags: ["sop", "procedure", "process", "workflow"],
  },
  {
    id: "risk-register",
    category: "management-risk",
    title: "Risk register and treatment plan",
    description: "Practical enterprise or project risk register with scoring, owners, treatments and review cadence.",
    from: 250,
    unit: "per register",
    tags: ["risk register", "erm", "treatment", "governance"],
  },
  {
    id: "policy-drafting",
    category: "management-risk",
    title: "Business policy drafting",
    description: "One tailored policy with responsibilities, control requirements, exceptions and approval history.",
    from: 180,
    unit: "per policy",
    tags: ["policy", "governance", "controls", "compliance"],
  },
  {
    id: "kpi-dashboard",
    category: "management-risk",
    title: "KPI dashboard design",
    description: "A focused metric set, definitions, owners, data sources and management-ready dashboard layout.",
    from: 250,
    unit: "per dashboard",
    tags: ["kpi", "dashboard", "metrics", "performance"],
  },
  {
    id: "operational-review",
    category: "management-risk",
    title: "Operational process review",
    description: "Focused review of workflow, capacity, hand-offs, delays, waste and control points, with improvement actions.",
    from: 500,
    unit: "per process",
    tags: ["operations", "process improvement", "efficiency", "controls"],
  },
  {
    id: "ai-governance-readiness",
    category: "management-risk",
    title: "AI governance and controls readiness",
    description: "Use-case inventory, risk classification, responsibility model, policy baseline and evidence roadmap.",
    from: 600,
    unit: "per assessment",
    tags: ["ai governance", "ai act", "controls", "risk"],
  },

  {
    id: "funding-fit-check",
    category: "loan-funding",
    title: "Funding fit and fee check",
    description: "A short initial review of the objective, applicant profile, likely route and evidence readiness.",
    from: 0,
    unit: "initial check",
    free: true,
    popular: true,
    tags: ["free", "eligibility", "grant", "loan", "fit check"],
  },
  {
    id: "funding-route-map",
    category: "loan-funding",
    title: "Funding route map",
    description: "Shortlist of plausible loan, FONDI.eu, Malta Enterprise or other routes with next-step requirements.",
    from: 150,
    unit: "per route map",
    tags: ["funding search", "route", "malta enterprise", "fondi"],
  },
  {
    id: "loan-readiness",
    category: "loan-funding",
    title: "Loan readiness assessment",
    description: "Review of borrowing purpose, repayment capacity, financial records, security and lender evidence gaps.",
    from: 200,
    unit: "per assessment",
    tags: ["loan", "readiness", "lender", "repayment"],
  },
  {
    id: "loan-application-pack",
    category: "loan-funding",
    title: "Loan application pack",
    description: "Coordinated application narrative, financial schedules, evidence index and lender-question preparation.",
    from: 450,
    unit: "per application",
    popular: true,
    tags: ["loan application", "bank", "lender", "evidence pack"],
  },
  {
    id: "funding-financial-model",
    category: "loan-funding",
    title: "Funding financial model",
    description: "Assumption-led projections, sources and uses, cash flow and sensitivity case for a financing request.",
    from: 300,
    unit: "per model",
    tags: ["financial model", "funding", "cash flow", "sensitivity"],
  },
  {
    id: "grant-project-design",
    category: "loan-funding",
    title: "Grant eligibility and project design",
    description: "Eligibility screen, intervention logic, outputs, milestones, risks and evidence requirements.",
    from: 350,
    unit: "per project",
    tags: ["grant", "eligibility", "project design", "outputs"],
  },
  {
    id: "grant-application",
    category: "loan-funding",
    title: "Grant application drafting",
    description: "Draft application narrative and coordinated annex list for a defined, straightforward funding call.",
    from: 750,
    unit: "per application",
    popular: true,
    tags: ["grant application", "funding call", "narrative", "annex"],
  },
  {
    id: "complex-eu-application",
    category: "loan-funding",
    title: "Complex EU or institutional application",
    description: "Full proposal coordination across work plan, partnership, indicators, budget, risk and annexes.",
    from: 1500,
    unit: "per application",
    tags: ["eu funding", "proposal", "partnership", "institutional"],
  },
  {
    id: "eligible-cost-budget",
    category: "loan-funding",
    title: "Eligible-cost and co-financing budget",
    description: "Detailed budget mapped to call rules, funding rate, co-financing and supporting quotations.",
    from: 250,
    unit: "per budget",
    tags: ["eligible costs", "budget", "co-financing", "grant"],
  },
  {
    id: "funding-evidence-pack",
    category: "loan-funding",
    title: "Loan or funding evidence pack",
    description: "Indexed, gap-checked pack of corporate, financial, tax, procurement and project evidence.",
    from: 300,
    unit: "per pack",
    tags: ["evidence", "funding", "loan", "documents"],
  },
  {
    id: "pitch-deck",
    category: "loan-funding",
    title: "Lender or funder pitch deck",
    description: "Concise decision-focused presentation aligned to the application narrative and financial case.",
    from: 350,
    unit: "per deck",
    tags: ["pitch deck", "lender", "funder", "presentation"],
  },
  {
    id: "award-drawdown-setup",
    category: "loan-funding",
    title: "Approval, award or drawdown setup",
    description: "Conditions-precedent tracker, responsibility map, evidence calendar and reporting setup after approval.",
    from: 300,
    unit: "per award",
    tags: ["award", "drawdown", "conditions precedent", "setup"],
  },
  {
    id: "grant-claim-report",
    category: "loan-funding",
    title: "Grant claim or donor report support",
    description: "Narrative, expenditure schedule and evidence-pack support for one routine claim or reporting period.",
    from: 300,
    unit: "per claim",
    tags: ["grant claim", "donor report", "expenditure", "evidence"],
  },

  {
    id: "contract-review",
    category: "legal-contracts",
    title: "Contract review",
    description: "Issue list, risk flags and suggested mark-ups for one standard commercial document of ordinary complexity.",
    from: 75,
    unit: "per document",
    popular: true,
    regulated: true,
    tags: ["contract review", "risk", "mark-up", "commercial"],
  },
  {
    id: "nda",
    category: "legal-contracts",
    title: "NDA or confidentiality agreement",
    description: "Mutual or one-way confidentiality document tailored to the parties, purpose, information and remedies.",
    from: 75,
    unit: "per document",
    regulated: true,
    tags: ["nda", "confidentiality", "agreement", "ip"],
  },
  {
    id: "services-agreement",
    category: "legal-contracts",
    title: "Services or consultancy agreement",
    description: "Tailored scope, fees, acceptance, liability, IP, confidentiality, termination and dispute clauses.",
    from: 175,
    unit: "per agreement",
    popular: true,
    regulated: true,
    tags: ["services agreement", "consultancy", "commercial contract", "terms"],
  },
  {
    id: "supplier-agreement",
    category: "legal-contracts",
    title: "Supplier or subcontractor agreement",
    description: "Practical commercial terms for deliverables, service levels, price, change, liability and exit.",
    from: 175,
    unit: "per agreement",
    regulated: true,
    tags: ["supplier", "subcontractor", "service level", "contract"],
  },
  {
    id: "employment-contractor-agreement",
    category: "legal-contracts",
    title: "Employment or contractor agreement",
    description: "Standard agreement tailored to the role, compensation, confidentiality, IP and termination structure.",
    from: 150,
    unit: "per agreement",
    regulated: true,
    tags: ["employment", "contractor", "staff", "agreement"],
  },
  {
    id: "terms-conditions",
    category: "legal-contracts",
    title: "Business terms and conditions",
    description: "Customer-facing trading terms aligned to the service, ordering, payment, liability and cancellation model.",
    from: 200,
    unit: "per document",
    regulated: true,
    tags: ["terms and conditions", "customer", "trading", "website"],
  },
  {
    id: "privacy-cookie-policy",
    category: "legal-contracts",
    title: "Privacy and cookie policy",
    description: "Plain-language policy based on the actual data flows, purposes, lawful bases, retention and user rights.",
    from: 175,
    unit: "per policy set",
    regulated: true,
    tags: ["privacy", "cookie", "gdpr", "data protection"],
  },
  {
    id: "data-processing-agreement",
    category: "legal-contracts",
    title: "Data processing agreement",
    description: "Controller-processor terms covering instructions, security, sub-processors, incidents and exit.",
    from: 150,
    unit: "per agreement",
    regulated: true,
    tags: ["dpa", "gdpr", "processor", "data protection"],
  },
  {
    id: "mou-loi",
    category: "legal-contracts",
    title: "Memorandum of understanding or letter of intent",
    description: "Clear statement of the proposed transaction, binding and non-binding terms, next steps and expiry.",
    from: 125,
    unit: "per document",
    regulated: true,
    tags: ["mou", "loi", "memorandum", "letter of intent"],
  },
  {
    id: "shareholders-agreement",
    category: "legal-contracts",
    title: "Shareholders’ agreement",
    description: "Governance, reserved matters, funding, transfer, leaver, deadlock and exit provisions for a simple structure.",
    from: 400,
    unit: "per agreement",
    regulated: true,
    tags: ["shareholders", "governance", "deadlock", "exit"],
  },
  {
    id: "contract-variation",
    category: "legal-contracts",
    title: "Contract variation or addendum",
    description: "Focused amendment that changes defined terms while preserving the original agreement’s structure.",
    from: 100,
    unit: "per document",
    regulated: true,
    tags: ["variation", "addendum", "amendment", "contract"],
  },
  {
    id: "legal-compliance-memo",
    category: "legal-contracts",
    title: "Legal research or compliance memo",
    description: "Issue-focused research with sources, assumptions, practical implications and questions for warranted counsel.",
    from: 250,
    unit: "per issue",
    regulated: true,
    tags: ["legal research", "compliance", "memo", "regulation"],
  },
];

export function formatCataloguePrice(service: CatalogueService) {
  return service.free ? "Free" : `From €${service.from.toLocaleString("en")}`;
}
